### ISSUE TITLE
Problems when using uncalled4 for event_detect

### ISSUE THREAD

**Issue by Happy0430room** [skovaka/uncalled4#20]
Hi, Sam,

I' m trying to use uncalled4 for event detector, it works well when I am trying r9.4 model, but when I am trying r10.4 model, the result of event detector (`read.events["mean"]`) seems the same no matter I set `PoreModel("dna_r10.4.1_400bps_9mer")` or `PoreModel("dna_r9.4.1_400bps_6mer")`, is there anything wrong? Maybe this normalize setting is for R9.4?
 `read = sp.process_signal(signal,normalize=True) 
`

```m_r9 = PoreModel("dna_r9.4.1_400bps_6mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file
m_r10 = PoreModel("dna_r10.4.1_400bps_9mer") #or "dna_r10.4.1_400bps_9mer", "rna_r9.4.1_70bps_5mer", custom TSV file
c = Config()
c.event_detector = EventDetector.PRMS_450BPS #or EventDetector.PRMS_70BPS
sp = SignalProcessor(m_r9,c) #sp = SignalProcessor(m_r10,c)
read = sp.process_signal(signal,normalize=True) #signal should be numpy array/list of un-normalized raw sample values

print(read.events["mean"])    #event current means
#print(read.events["stdv"])    #event current stdvs
# print(read.events["start"])   #event sample starts
# print(read.events["length"])  #event sample lengths
print(read.signal)            #normalized raw signal (using method-of-moments) 
```
Because I'm trying to map the raw signal to the reference, in my new method (for hardware).  If one event value is 86.486336 (for example), which is also the value of k-mer 'AAAAAA' , I would regard this event is similar to k-mer 'AAAAAA'. It works well when I'm trying R9.4 dataset. 

But when I'm trying R10.4 model,which seems have been normalized, mean value of kmer model is 0, std is 1. The event from event_detector from UNCALLED4 seems still around 90. I try to normalize the event from uncalled4 to the standard units, and map this normalized event with reference just the same method as R9.4, the results are not very good. I'm not sure whether the event detector is suitable for R10.4 model, and is it ok to normalize the event and then compare with the model?

Thank you very much.

**Comment by skovaka** [comment]
Event detection does not perform normalization or depend on the pore model, only the set of parameters in `Config.event_detector`, which you correctly set to `EventDetector.PRMS_450BPS` for both r10 and r9 since they run at similar speeds. I intended `SignalProcessor` to combine event detection with normalization, but I went through a few iterations of how to normalize and I didn't end up using `process_signal(...,normalize=True)` in the final implementation, and I should either remove or rewrite that parameter since it doesn't behave how it should. I suggest keeping the default `normalize=False` and normalizing the event means yourself after event detection

**Comment by Happy0430room** [comment]
Sorry, I'm not very clear about how you do the final nomalization step in UNCALLED4. Because I think I can use `sp.set_norm_tgt(0, 1) #mean,stdv` to set the parameter for normalization, why you don't choose the `process_signal(...,normalize=True)` finally.

**Comment by skovaka** [comment]
I think you're right that if you set `sp.set_norm_tgt(0, 1)` then  `process_signal(...,normalize=True)` should scale the read such that the mean=0 and stdv=1, which is a reasonable approximate normalization method that assumes a perfectly random k-mer distribution. Your initial issue was because the default target isn't scaled consistently between r9 and r10, which I will fix in the future, but if you explicitly set the target it should work. 

Uncalled4 normalizes in two iterations. The first iteration scales the signal to match the mean and standard deviation of the expected current of the k-mers from the reference sequence within the coordinates defined by the minimap2 alignment, so if you know the expected reference current levels that would be equivalent to `sp.set_norm_tgt(reference_current.mean(), reference_current.stdv())`. The second iteration performs linear regression between the aligned read and reference currents, using the computed slope as the "scale" and the intercept as the "shift" parameters. Sorry if the preprint description is a bit vague, I'm working on illustrating the normalization method more thoroughly for manuscript revisions!

**Comment by Happy0430room** [comment]
Thank you very much! It's very clear now I think!
